### ISSUE TITLE
getting error while using this theme 

### ISSUE THREAD

**Issue by AshutoshSajan** [drofloh/oh-my-zsh-custom#4]
I have installed the theme and other plugins autosuggestion and syntax highlighting etc are not working and I am getting these error with that,
![Screenshot from 2020-04-08 17-04-40](https://user-images.githubusercontent.com/44765540/78779743-149e8600-79bb-11ea-9a27-7dfff4597122.png)

prompt_battery:[:3: unknown condition: -gt                                                                                                                                   
prompt_battery:[:6: unknown condition: -gt
prompt_battery:[:9: unknown condition: -gt
prompt_battery:[:12: unknown condition: -gt
prompt_battery:[:15: unknown condition: -gt

**Comment by kurkutesa** [comment]
Beautiful theme perfectly runs on MacOS; but on Linux I am getting the same error mentioned by @sajan1231. Please suggest how to resolve it.

**Comment by kurkutesa** [comment]
Well, I guess I have figured it out. For me the the error goes away when I have modified the `~/.oh-my-zsh/custom/themes/oh-my-zsh-custom/custom/drofloh_functions.zsh` script. Near `line # 92` in the zsh script file , I have replaced all the **if condition's** single square brackets `[    ]` with the double square brackets`[[     ]]` ... 
Before : 

>   battery_perc=$(battery_pct)
 ` if [ $battery_perc -gt 90 ]; then`
    icon=$ICONS[battery_full]
    batt_col=$fg[green]

After :

>    battery_perc=$(battery_pct)
 ` if [[ $battery_perc -gt 90 ]]; then`
    icon=$ICONS[battery_full]
    batt_col=$fg[green]

> 
I hope it helps.

**Comment by drofloh** [comment]
> Well, I guess I have figured it out. For me the the error goes away when I have modified the `~/.oh-my-zsh/custom/themes/oh-my-zsh-custom/custom/drofloh_functions.zsh` script. Near `line # 92` in the zsh script file , I have replaced all the **if condition's** single square brackets `[    ]` with the double square brackets`[[     ]]` ... 
> 
> Before : 
> 
> 
> 
> >   battery_perc=$(battery_pct)
> 
>  ` if [ $battery_perc -gt 90 ]; then`
> 
>     icon=$ICONS[battery_full]
> 
>     batt_col=$fg[green]
> 
> 
> 
> After :
> 
> 
> 
> >    battery_perc=$(battery_pct)
> 
>  ` if [[ $battery_perc -gt 90 ]]; then`
> 
>     icon=$ICONS[battery_full]
> 
>     batt_col=$fg[green]
> 
> 
> 
> > 
> 
> I hope it helps.

Hey thanks for the feedback, am not too active on this account, when I come to work on this again I’ll be sure to add in the fix, I only ever use on macOS so not surprised it didn’t work first time on Linux.

**Comment by drofloh** [comment]
Should be updated now.
