### ISSUE TITLE
Problem with different battery level  

### ISSUE THREAD

**Issue by inkkim** [drofloh/oh-my-zsh-custom#6]
I love your custom, Thanks for sharing your work.

I'm a MacOS user and I found some issue which is differentiation of battery level between on system and custom.

sometime, custom battery level is less than system.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/60086878/94991284-0d98af00-05bd-11eb-93cd-05c9902ace12.png">

I adjusted like this
<img width="717" alt="image" src="https://user-images.githubusercontent.com/60086878/94991228-a24edd00-05bc-11eb-99f1-894168f88721.png">

It works!
<img width="717" alt="image" src="https://user-images.githubusercontent.com/60086878/94991291-1ee1bb80-05bd-11eb-9c76-4546ac0feefa.png">

**Comment by drofloh** [comment]
> I love your custom, Thanks for sharing your work.
> 
> 
> 
> I'm a MacOS user and I found some issue which is differentiation of battery level between on system and custom.
> 
> 
> 
> sometime, custom battery level is less than system.
> 
> <img width="717" alt="image" src="https://user-images.githubusercontent.com/60086878/94991284-0d98af00-05bd-11eb-93cd-05c9902ace12.png">
> 
> 
> 
> I adjusted like this
> 
> <img width="717" alt="image" src="https://user-images.githubusercontent.com/60086878/94991228-a24edd00-05bc-11eb-99f1-894168f88721.png">
> 
> 
> 
> It works!
> 
> <img width="717" alt="image" src="https://user-images.githubusercontent.com/60086878/94991291-1ee1bb80-05bd-11eb-9c76-4546ac0feefa.png">
> 
> 
> 
> 
> 
> 

Hey thanks for the feedback. Have updated the code as per your recommendation. 
Cheers
Andy.
