### ISSUE TITLE
font and icons do not display properly

### ISSUE THREAD

**Issue by GeekRicardo** [drofloh/oh-my-zsh-custom#7]
I installed all the `nerd` fonts, and rebooted my system:
![image](https://user-images.githubusercontent.com/35123328/98921560-6c324080-250c-11eb-95f4-de0308ab2d2a.png)
some solutions?

**Comment by arnoob16** [comment]
@GeekRicardo I'm assuming you fixed it yourself, so can you tell me how you fixed it? Installed the font and rebooted the system still the same issue.
